### PR TITLE
Add support for handling enums with negative indexes

### PR DESCRIPTION
**Pull request by jonathanp**

### CODE REVIEW

**Comment by ffMathy** [comment]
Looks good to me. Do you have anything to add @Evertras?

And I can merge the pull request, but I am a little confused - have you set me as owner yet? Because in that case I need to reintegrate the `ffMathy` version into this one first.

**Comment by jonathanp** [comment]
@ffMathy Your fork seems to be in sync with this repo, what do you mean by reintegrating your fork into this one?

**Comment by Evertras** [comment]
I gotcha on this one.  ffMathy, is there something you need that ownership gives you in particular?

**Comment by ffMathy** [comment]
Yes, because this is all kind of a mess now. 

Don't get me wrong. It's just that the current Readme on this repository points to my repository link wise,  and this repository has all the pull requests. It would therefore be nice to shut down my repository and count this as the official one. 

Or do the opposite and shut down this one, making you an owner.

**Comment by Evertras** [comment]
Yeah, that needs to get cleaned up.

The only way I can make you the owner is to transfer it to github.com/ffMathy, and I'm afraid that will break things in other ways.  The owner is in the URL.  Would you be up for shutting down yours and working off this one?

**Comment by ffMathy** [comment]
Alternatively @Evertras, could we transfer ownership to mine, and then you could fork it, naming it the same?

That way backward compatibility won't be broken, and the ownership will be truly transferred with pull requests etc.

**Comment by Evertras** [comment]
Actually, after researching this a bit, it looks like there will be a clean redirect in place if I transfer it to you.  I think I actually shouldn't even have a fork, I'll just make any personal PRs or comments on the one in your name.  Sound good?  You'll have to delete your fork entirely, then I'll transfer it, then everything should actually work pretty well from there.

**Comment by ffMathy** [comment]
Sounds great! I have deleted my fork.

**Comment by Evertras** [comment]
Transfer requested.  WTB PMs in GitHub.

Also delete your gulp plugin fork and I can transfer that one too if you'd like.

**Comment by Evertras** [comment]
> When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete.

Let me know if you didn't get the e-mail.

**Comment by ffMathy** [comment]
I will look now.

**Comment by ffMathy** [comment]
It hasn't arrived yet.

**Comment by ffMathy** [comment]
Yup!

**Comment by ffMathy** [comment]
I deleted the gulp repo as well, could you transfer that too?

**Comment by Evertras** [comment]
Great!  Request sent for the gulp one as well.

**Pull request merged**
