### PR TITLE
Added support for methods and more

### PR DESCRIPTION
**Pull request by ffMathy**
- Added support for methods including parameters.
- Removed `prefixWithI` option and instead made a more flexible `interfaceNameResolver` that can be specified in the options.
- Added new tests to cover new functionality.
- Extracted functionality for inferring the type of something into a separate reusable method.
- Added `async` support by removing the `Task` around `async` methods in the emitted TypeScript.

_Let me know if there is anything I can improve on this or work on for it to be merged, and let me know what you think._

### CODE REVIEW

**Comment by ffMathy** [comment]
The reason is that an `interfaceNameResolver` offers more flexibility.

We use Knockout JS at work, and we want to generate two types of models from our C# classes.

So let's say we have the following POCO:

```
public class MyPoco {
    public string Foo { get; set; }
    public int Bar { get; set; }
}
```

I actually want to generate two interfaces. One that represents a Knockout ViewModel, and one that represents the raw POCO:

```
interface MyPoco {
    Foo: string;
    Bar: number;
}
```

And:

```
interface MyPocoKnockoutViewModel {
    Foo: ko.Observable<string>;
    Bar: ko.Observable<number>;
}
```

This can be done with the following options:

```
{
    typeResolver: function (typeName, scope) { 
        if(scope !== "property-type") return typeName; //only change the type name for property types
        return "Observable<" + typeName + ">"; 
    },
    interfaceNameResolver: function(interfaceName) {
        return interfaceName + "KnockoutViewModel";
    }
}
```

Furthermore, the `interfaceNameResolver` could just as easily be modified to prefix `I` in type names, that's why I removed the old setting.

Does that make sense? See my updated documentation here for all the stuff I added:
- https://github.com/ffMathy/typescript-cs-poco

**Comment by Evertras** [comment]
I think that's a fantastic addition, but can we keep the old option as well?  It's a little bit dirty and 'legacy' but it's something people are already using, and I don't want to implement breaking changes if we can avoid it.

Also, if it's not painfully obvious, I've been a bit lax on keeping this project updated as I am no longer actively using it myself.  It's obvious you guys are getting some good use out of it.  Would you be interested in taking this on?

**Comment by ffMathy** [comment]
Wow, what an honor! I would love to take over the project, and I don't think I would disappoint. Feel free to set me as administrator for the project.

Also, check out the latest commit I just made. Does it fit the needs?

**Comment by Evertras** [comment]
Yep, merged, thanks!  Going forward all I ask is that no existing tests be removed.  I'll start working on transferring stuff over to you so this can stay alive and updated for everyone to make use of.

**Comment by ffMathy** [comment]
I understand! I have also referenced 3 issues that I believe are solved with this pull request.

**Comment by Evertras** [comment]
Great!  I've added you as a collaborator on here, let me know if that's not enough access.  I'm not averse to transferring ownership entirely, I just don't want issues to vanish.  Let me know if you want to work that out.

I'll have to wait until I get home from work and have SSH access to the outside world again before I can add you as an owner on NPM as well so you have publish permissions, and I'll publish 1.11.0 at that time as well with your changes.

**Comment by ffMathy** [comment]
Perfect! Well, more access would be convenient, but I think current access is good. As long as you don't abandon the project entirely and I can always get in touch with you for desperate times, then all is good.

**Pull request merged**
