### PR TITLE
add support for abstract base classes and for ignoring specific inherited objects

### PR DESCRIPTION
**Pull request by kevinphelps**

### CODE REVIEW

**Comment by kevinphelps** [comment]
Thanks for this tool! And thanks for letting me contribute. :)

**Comment by kevinphelps** [comment]
So this pull request is for two things:
1. Abstract classes were being missed resulting in missing parent interfaces in the TypeScript in my case. I fixed this with a simple change to the regular expression for detecting types.

2. All of my C# DTO objects inherit a common abstract base class which in turn inherits an interface that my service layer uses for conversion, permissions, etc. The abstract base class is not being converted, but it also inherits an interface. I don't care about this interface in TypeScript because everything it exposes is on the classes anyway. So I needed a way to ignore it. This change allows the user to pass an option named 'ignoreInheritance' which is an array of names to ignore when generating the 'extends ****' for the TypeScript.

**Comment by Evertras** [comment]
Kevin, I want to apologize for not getting to this sooner.  Crunch at work distracted me. :(

Merging this now.

**Comment by Evertras** [comment]
Published to NPM as 1.7.0

**Pull request merged**
